controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_product_index_orderby_name:
    path: /products/order-by-name
    controller: App\Controller\ProductController::index
    methods: ['GET']
    
app_product_index_orderby_date:
    path: /products/order-by-date
    controller: App\Controller\ProductController::index
    methods: ['GET']
